CREATE TABLE your_table (
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMP,
    startbahnhof TEXT,
    endbahnhof TEXT,
    step1_slot1 double precision,
    step1_slot2 double precision,
    step1_slot3 double precision,
    step1_slot4 double precision,
    step1_slot5 double precision,
    step1_slot6 double precision,
    step2_slot1 double precision,
    step2_slot2 double precision,
    step2_slot3 double precision,
    step2_slot4 double precision,
    step2_slot5 double precision,
    step2_slot6 double precision,
    step3_slot1 double precision,
    step3_slot2 double precision,
    step3_slot3 double precision,
    step3_slot4 double precision,
    step3_slot5 double precision,
    step3_slot6 double precision,
    step4_slot1 double precision,
    step4_slot2 double precision,
    step4_slot3 double precision,
    step4_slot4 double precision,
    step4_slot5 double precision,
    step4_slot6 double precision,
    step5_slot1 double precision,
    step5_slot2 double precision,
    step5_slot3 double precision,
    step5_slot4 double precision,
    step5_slot5 double precision,
    step5_slot6 double precision
);